param:
  inputfile: "queris.csv"
  
  database:
    -   type: "mysql"
        protocol: "mysql"
        host: "localhost" 
        port: 3306
        name: ""
        username: ""
        password: ""
        
    -   type: "oracle"
        protocol: "oracle:thin:@"
        host: "localhost"
        port: 1521 
        name: ""
        username: ""
        password: ""
        
    -   type: "sqlserver"
        protocol: "sqlserver"
        host: "localhost"
        port: 1433
        name: ""
        username: ""
        password: ""
        
    -   type: "postgres"
        protocol: "postgresql"
        host: "localhost"
        port: 5432
        name: ""
        username: ""
        password: ""